/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminAuthedRouteImport } from './routes/admin/_authed'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ArticlesSlugRouteImport } from './routes/articles/$slug'
import { Route as ImagesSplatRouteImport } from './routes/images/$'
import { Route as OgSlugRouteImport } from './routes/og/$slug'
import { Route as AdminAuthedIndexRouteImport } from './routes/admin/_authed/index'
import { Route as AdminAuthedArticlesNewRouteImport } from './routes/admin/_authed/articles/new'
import { Route as AdminAuthedArticlesIdEditRouteImport } from './routes/admin/_authed/articles/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedRoute = AdminAuthedRouteImport.update({
  id: '/admin/_authed',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesSlugRoute = ArticlesSlugRouteImport.update({
  id: '/articles/$slug',
  path: '/articles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesSplatRoute = ImagesSplatRouteImport.update({
  id: '/images/$',
  path: '/images/$',
  getParentRoute: () => rootRouteImport,
} as any)
const OgSlugRoute = OgSlugRouteImport.update({
  id: '/og/$slug',
  path: '/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthedIndexRoute = AdminAuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedArticlesNewRoute = AdminAuthedArticlesNewRouteImport.update({
  id: '/articles/new',
  path: '/articles/new',
  getParentRoute: () => AdminAuthedRoute,
} as any)
const AdminAuthedArticlesIdEditRoute =
  AdminAuthedArticlesIdEditRouteImport.update({
    id: '/articles/$id/edit',
    path: '/articles/$id/edit',
    getParentRoute: () => AdminAuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/admin': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/images/$': typeof ImagesSplatRoute
  '/og/$slug': typeof OgSlugRoute
  '/admin/': typeof AdminAuthedIndexRoute
  '/admin/articles/new': typeof AdminAuthedArticlesNewRoute
  '/admin/articles/$id/edit': typeof AdminAuthedArticlesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/admin/login': typeof AdminLoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/images/$': typeof ImagesSplatRoute
  '/og/$slug': typeof OgSlugRoute
  '/admin': typeof AdminAuthedIndexRoute
  '/admin/articles/new': typeof AdminAuthedArticlesNewRoute
  '/admin/articles/$id/edit': typeof AdminAuthedArticlesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/admin/_authed': typeof AdminAuthedRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/articles/$slug': typeof ArticlesSlugRoute
  '/images/$': typeof ImagesSplatRoute
  '/og/$slug': typeof OgSlugRoute
  '/admin/_authed/': typeof AdminAuthedIndexRoute
  '/admin/_authed/articles/new': typeof AdminAuthedArticlesNewRoute
  '/admin/_authed/articles/$id/edit': typeof AdminAuthedArticlesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/admin'
    | '/admin/login'
    | '/articles/$slug'
    | '/images/$'
    | '/og/$slug'
    | '/admin/'
    | '/admin/articles/new'
    | '/admin/articles/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/admin/login'
    | '/articles/$slug'
    | '/images/$'
    | '/og/$slug'
    | '/admin'
    | '/admin/articles/new'
    | '/admin/articles/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/admin/_authed'
    | '/admin/login'
    | '/articles/$slug'
    | '/images/$'
    | '/og/$slug'
    | '/admin/_authed/'
    | '/admin/_authed/articles/new'
    | '/admin/_authed/articles/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  AdminAuthedRoute: typeof AdminAuthedRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ArticlesSlugRoute: typeof ArticlesSlugRoute
  ImagesSplatRoute: typeof ImagesSplatRoute
  OgSlugRoute: typeof OgSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed': {
      id: '/admin/_authed'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$slug': {
      id: '/articles/$slug'
      path: '/articles/$slug'
      fullPath: '/articles/$slug'
      preLoaderRoute: typeof ArticlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images/$': {
      id: '/images/$'
      path: '/images/$'
      fullPath: '/images/$'
      preLoaderRoute: typeof ImagesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/og/$slug': {
      id: '/og/$slug'
      path: '/og/$slug'
      fullPath: '/og/$slug'
      preLoaderRoute: typeof OgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_authed/': {
      id: '/admin/_authed/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAuthedIndexRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/articles/new': {
      id: '/admin/_authed/articles/new'
      path: '/articles/new'
      fullPath: '/admin/articles/new'
      preLoaderRoute: typeof AdminAuthedArticlesNewRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
    '/admin/_authed/articles/$id/edit': {
      id: '/admin/_authed/articles/$id/edit'
      path: '/articles/$id/edit'
      fullPath: '/admin/articles/$id/edit'
      preLoaderRoute: typeof AdminAuthedArticlesIdEditRouteImport
      parentRoute: typeof AdminAuthedRoute
    }
  }
}

interface AdminAuthedRouteChildren {
  AdminAuthedIndexRoute: typeof AdminAuthedIndexRoute
  AdminAuthedArticlesNewRoute: typeof AdminAuthedArticlesNewRoute
  AdminAuthedArticlesIdEditRoute: typeof AdminAuthedArticlesIdEditRoute
}

const AdminAuthedRouteChildren: AdminAuthedRouteChildren = {
  AdminAuthedIndexRoute: AdminAuthedIndexRoute,
  AdminAuthedArticlesNewRoute: AdminAuthedArticlesNewRoute,
  AdminAuthedArticlesIdEditRoute: AdminAuthedArticlesIdEditRoute,
}

const AdminAuthedRouteWithChildren = AdminAuthedRoute._addFileChildren(
  AdminAuthedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  AdminAuthedRoute: AdminAuthedRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ArticlesSlugRoute: ArticlesSlugRoute,
  ImagesSplatRoute: ImagesSplatRoute,
  OgSlugRoute: OgSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
